=== api-evangelist/openverse/json-schema/paginatedaudiolist.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://api.openverse.org/v1/schema/PaginatedAudioList",
  "title": "PaginatedAudioList",
  "type": "object",
  "properties": {
    "result_count": {
      "type": "integer",
      "description": "The total number of items returned by search result.",
      "example": 10000
    },
    "page_count": {
      "type": "integer",
      "description": "The total number of pages returned by search result.",
      "example": 20
    },
    "page_size": {
      "type": "integer",
      "description": "The number of items per page.",
      "example": 20
    },
    "page": {
      "type": "integer",
      "description": "The current page number returned in the response.",
      "example": 1
    },
    "results": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/Audio"
      }
    },
    "warnings": {
      "type": "array",
      "items": {
        "type": "object"
      },
      "description": "Warnings pertinent to the request. If there are no warnings, this property will not be present on the response. Warnings are non-critical problems with the request. Responses with warnings should be treated as unstable. Warning descriptions must not be treated as machine readable and their schema can change at any time.",
      "example": [
        {
          "code": "partially invalid request parameter",
          "message": "Some of the request parameters were bad, but we were able to process the request. Here's some information that might help you fix the problem for future requests."
        }
      ]
    }
  },
  "required": [
    "page_count",
    "page_size",
    "page",
    "results",
    "result_count"
  ]
}

=== api-evangelist/openverse/examples/audio_search_200.json
{
  "result_count": 10000,
  "page_count": 20,
  "page_size": 20,
  "page": 1,
  "results": [
    {
      "id": "8624ba61-57f1-4f98-8a85-ece206c319cf",
      "title": "Wish You Were Here",
      "indexed_on": "2022-12-06T06:54:25Z",
      "foreign_landing_url": "https://www.jamendo.com/track/1214935",
      "url": "https://mp3d.jamendo.com/download/track/1214935/mp32",
      "creator": "The.madpix.project",
      "creator_url": "https://www.jamendo.com/artist/441585/the.madpix.project",
      "license": "by-nc-sa",
      "license_version": "3.0",
      "license_url": "https://creativecommons.org/licenses/by-nc-sa/3.0/",
      "provider": "jamendo",
      "source": "jamendo",
      "category": "music",
      "genres": [
        "dance",
        "electronic",
        "house"
      ],
      "filesize": 7139840,
      "filetype": "mp3",
      "tags": [
        {
          "accuracy": null,
          "name": "vocal",
          "unstable__provider": "jamendo"
        },
        {
          "accuracy": null,
          "name": "female",
          "unstable__provider": "jamendo"
        },
        {
          "accuracy": null,
          "name": "speed_medium",
          "unstable__provider": "jamendo"
        },
        {
          "accuracy": null,
          "name": "guitar",
          "unstable__provider": "jamendo"
        },
        {
          "accuracy": null,
          "name": "strings",
          "unstable__provider": "jamendo"
        },
        {
          "accuracy": null,
          "name": "energetic",
          "unstable__provider": "jamendo"
        },
        {
          "accuracy": null,
          "name": "acoustic",
          "unstable__provider": "jamendo"
        },
        {
          "accuracy": null,
          "name": "vocal",
          "unstable__provider": "jamendo"
        },
        {
          "accuracy": null,
          "name": "voice",
          "unstable__provider": "jamendo"
        },
        {
          "accuracy": null,
          "name": "funkyhouse",
          "unstable__provider": "jamendo"
        }
      ],
      "alt_files": null,
      "attribution": "\"Wish You Were Here\" by The.madpix.project is licensed under CC BY-NC-SA 3.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/3.0/.",
      "fields_matched": [
        "title"
      ],
      "mature": false,
      "audio_set": {
        "title": "Wish You Were Here",
        "foreign_landing_url": "https://www.jamendo.com/album/145774/wish-you-were-here",
        "creator": "The.madpix.project",
        "creator_url": "https://www.jamendo.com/artist/441585/the.madpix.project",
        "url": "https://usercontent.jamendo.com?type=album&id=145774&width=200",
        "filesize": null,
        "filetype": null
      },
      "duration": 270000,
      "bit_rate": 128000,
      "sample_rate": 44100,
      "thumbnail": "https://api.openverse.org/v1/audio/8624ba61-57f1-4f98-8a85-ece206c319cf/thumb/",
      "detail_url": "https://api.openverse.org/v1/audio/8624ba61-57f1-4f98-8a85-ece206c319cf/",
      "related_url": "https://api.openverse.org/v1/audio/8624ba61-57f1-4f98-8a85-ece206c319cf/related/",
      "waveform": "https://api.openverse.org/v1/audio/8624ba61-57f1-4f98-8a85-ece206c319cf/waveform/",
      "unstable__sensitivity": []
    }
  ],
  "warnings": [
    {
      "code": "partially invalid request parameter",
      "message": "Some of the request parameters were bad, but we were able to process the request. Here's some information that might help you fix the problem for future requests."
    }
  ]
}

=== api-evangelist/openverse/examples/images_search_200.json
{
  "result_count": 10000,
  "page_count": 20,
  "page_size": 20,
  "page": 1,
  "results": [
    {
      "id": "4bc43a04-ef46-4544-a0c1-63c63f56e276",
      "title": "Tree Bark Photo",
      "indexed_on": "2022-08-27T17:39:48Z",
      "foreign_landing_url": "https://stocksnap.io/photo/XNVBVXO3B7",
      "url": "https://cdn.stocksnap.io/img-thumbs/960w/XNVBVXO3B7.jpg",
      "creator": "Tim Sullivan",
      "creator_url": "https://www.secretagencygroup.com",
      "license": "cc0",
      "license_version": "1.0",
      "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "provider": "stocksnap",
      "source": "stocksnap",
      "category": "photograph",
      "filesize": 896128,
      "filetype": "jpg",
      "tags": [
        {
          "accuracy": null,
          "name": "tree",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "bark",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "texture",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "wood",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "nature",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "pattern",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "rough",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "surface",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "brown",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "old",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "background",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "trunk",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "natural",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "forest",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "detail",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "lumber",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "weathered",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "timber",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "stump",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "closeup",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": null,
          "name": "root",
          "unstable__provider": "stocksnap"
        },
        {
          "accuracy": 0.95,
          "name": "tree",
          "unstable__provider": "machine_example"
        },
        {
          "accuracy": 0.9,
          "name": "bark",
          "unstable__provider": "machine_example"
        },
        {
          "accuracy": 0.98,
          "name": "plant",
          "unstable__provider": "machine_example"
        }
      ],
      "attribution": "\"Tree Bark Photo\" by Tim Sullivan is marked with CC0 1.0. To view the terms, visit https://creativecommons.org/publicdomain/zero/1.0/.",
      "fields_matched": [
        "title"
      ],
      "mature": false,
      "height": 4016,
      "width": 6016,
      "thumbnail": "https://api.openverse.org/v1/images/4bc43a04-ef46-4544-a0c1-63c63f56e276/thumb/",
      "detail_url": "https://api.openverse.org/v1/images/4bc43a04-ef46-4544-a0c1-63c63f56e276/",
      "related_url": "https://api.openverse.org/v1/images/4bc43a04-ef46-4544-a0c1-63c63f56e276/related/",
      "unstable__sensitivity": []
    }
  ],
  "warnings": [
    {
      "code": "partially invalid request parameter",
      "message": "Some of the request parameters were bad, but we were able to process the request. Here's some information that might help you fix the problem for future requests."
    }
  ]
}

=== api-evangelist/openverse/examples/audio_related_200.json
{
  "result_count": 10000,
  "page_count": 20,
  "page_size": 20,
  "page": 1,
  "results": [
    {
      "title": "File:Mozart - Eine kleine Nachtmusik - 1. Allegro.ogg",
      "id": "36537842-b067-4ca0-ad67-e00ff2e06b2e",
      "creator": "Wolfgang Amadeus Mozart",
      "creator_url": "https://en.wikipedia.org/wiki/Wolfgang_Amadeus_Mozart",
      "url": "https://upload.wikimedia.org/wikipedia/commons/2/24/Mozart_-_Eine_kleine_Nachtmusik_-_1._Allegro.ogg",
      "provider": "wikimedia",
      "source": "wikimedia",
      "license": "by-sa",
      "license_version": "2.0",
      "license_url": "https://creativecommons.org/licenses/by-sa/2.0/",
      "foreign_landing_url": "https://commons.wikimedia.org/w/index.php?curid=3536953",
      "detail_url": "https://api.openverse.org/v1/audio/36537842-b067-4ca0-ad67-e00ff2e06b2e",
      "related_url": "https://api.openverse.org/v1/recommendations/audio/36537842-b067-4ca0-ad67-e00ff2e06b2e",
      "fields_matched": [
        "description",
        "title"
      ],
      "tags": [
        {
          "name": "exam"
        },
        {
          "name": "tactics"
        }
      ]
    }
  ],
  "warnings": [
    {
      "code": "partially invalid request parameter",
      "message": "Some of the request parameters were bad, but we were able to process the request. Here's some information that might help you fix the problem for future requests."
    }
  ]
}

=== api-evangelist/openverse/examples/images_related_200.json
{
  "result_count": 10000,
  "page_count": 20,
  "page_size": 20,
  "page": 1,
  "results": [
    {
      "title": "exam tactics",
      "id": "610756ec-ae31-4d5e-8f03-8cc52f31b71d",
      "creator": "Sean MacEntee",
      "creator_url": "https://www.flickr.com/photos/18090920@N07",
      "tags": [
        {
          "name": "exam"
        },
        {
          "name": "tactics"
        }
      ],
      "url": "https://live.staticflickr.com/4065/4459771899_07595dc42e.jpg",
      "thumbnail": "https://api.openverse.org/v1/thumbs/610756ec-ae31-4d5e-8f03-8cc52f31b71d",
      "provider": "flickr",
      "source": "flickr",
      "license": "by",
      "license_version": "2.0",
      "license_url": "https://creativecommons.org/licenses/by/2.0/",
      "foreign_landing_url": "https://www.flickr.com/photos/18090920@N07/4459771899",
      "detail_url": "https://api.openverse.org/v1/images/610756ec-ae31-4d5e-8f03-8cc52f31b71d",
      "related_url": "https://api.openverse.org/v1/recommendations/images/610756ec-ae31-4d5e-8f03-8cc52f31b71d"
    }
  ],
  "warnings": [
    {
      "code": "partially invalid request parameter",
      "message": "Some of the request parameters were bad, but we were able to process the request. Here's some information that might help you fix the problem for future requests."
    }
  ]
}
